[general]
live_config_reload = true

[window]
opacity = 0.95
padding = { x = 5, y = 5 }
startup_mode = "Maximized"
title = "Alacritty"
dynamic_title = false

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Med" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font Mono", style = "Bold Italic" }
size = 11
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true

[cursor]
style = { shape = "Beam", blinking = "On" }
vi_mode_style = { shape = "Block", blinking = "On" }
unfocused_hollow = false

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

# Colors (One Dark)

# Default colors
[colors.primary]
background = '#282c34'
foreground = '#abb2bf'

# Normal colors
[colors.normal]
black = '#1e2127'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#abb2bf'

# Bright colors
[colors.bright]
black = '#5c6370'
red = '#e06c75'
green = '#98c379'
yellow = '#d19a66'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#ffffff'
